name: ${project.name}
version: ${project.version}
author: ${author}
description: FaraMC Practice Core Plugin made by siwoolol the best man alive
main: lol.siwoo.faramcpracticecore.FaraMCPracticeCore
load: POSTWORLD
website: siwoo.lol

api-version: 1.8.8

libraries:
  - org.openjdk.nashorn:nashorn-core:15.4

softdepend: [ Luckperms, Multiverse-Core ]

permissions:
  faramcpracticecore.admin:
    description: "Literally Admin"
    default: op
    children:
      faramcpracticecore.fly: true
  faramcpracticecore.fly:
    description: "Allows You To Fly in the Lobby"

commands:
  fly:
    usage: "/fly"
    description: "Allows You To Fly"
  forcewin:
    usage: "/forcewin [round/match]"
    description: "Force Win the Fight/Round (Fight if Unspecified)"
  hurryuppartyowner:
    usage: "/hurryuppartyowner"
    description: "Hurry up party owner black man ahahahhahah"
  suggestgamemodetopartyowner:
    usage: "/suggestgamemodetopartyowner"
    description: "Suggest a Gamemode to Play to the owner of your Party"
  gmc:
    usage: "/gmc"
    description: "Gamemode Creative (Shortcut)"
  gms:
    usage: "/gms"
    description: "Gamemode Survival (Shortcut)"
  gmsp:
    usage: "/gmsp"
    description: "Gamemode Spectator (Shortcut)"
  gma:
    usage: "/gma"
    description: "Gamemode Adventure (Shortcut)"
  sudo:
    usage: "/sudo <target> [command/c:chat]"
  ai:
    usage: "/ai"
    description: "Toggle AI coach mode to improve your PvP skills"
